# Generated by Django 6.0.6 on 2026-06-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_user_is_first_login_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('loan_officer', 'Loan Officer'), ('auditor', 'Auditor/Viewer'), ('branch_manager', 'Branch Manager'), ('applicant', 'Loan Applicant')], default='loan_officer', max_length=20),
        ),
    ]
